### ISSUE TITLE
DynamoDB

### ISSUE THREAD

**Issue by surfy1h** [Sbolder/crypto-trading-app#1]
how do  you setup the DynamoDB tables for this project and connect to it via Lambda ?

thanks

**Comment by Sbolder** [comment]
![image](https://user-images.githubusercontent.com/23197084/214095802-d8161fd4-68d2-43c3-85d3-27b218fbe7ae.png)
![image](https://user-images.githubusercontent.com/23197084/214095877-c3ffd297-00ba-4cb1-ba0c-80cb2229381b.png)

the attached photo give you all information how create the 2 dynamodb table needed.

i'm sorry but unfortunalty i have't the time to create a cloudFormation template to create it.

To connect from lambda, there are a aws library for node in the code.
From aws env you need to set the Role of your lambda with correct permission "dynamodbFullAcceess"
From local env you need to se the credential with aws configure command and set the user with correct permission to access at dynamodb.

For any issue please contact me.

**Comment by Sbolder** [comment]
@surfy1h solved with this commit 7e8b0bcfa07fbf74d742b79c3d659c56e47f1c1d

under infrastructure folder you can find the dynamodb cloudformation and secretmanager cloudformation sample.

**Comment by surfy1h** [comment]
Thank you :)
